### ISSUE TITLE
Crash when going to meetings on a Process 

### ISSUE THREAD

**Issue by andreslucena** [decidim/metadecidim#10]
https://meta.decidim.barcelona/processes/welcome/f/168/ 

![imatge](https://user-images.githubusercontent.com/717367/34199355-caee619e-e56d-11e7-8031-d2af2fd4db59.png)

**Comment by xdubx** [comment]
Bug is no longer there. 
Close :D

**Comment by andreslucena** [comment]
@xbux you're right, I'm closing this issue.
