### ISSUE TITLE
Drop-down language selector for less than 4 locales

### ISSUE THREAD

**Issue by carolromero** [decidim/metadecidim#110]
**Describe the bug**
The language selector in the admin panel is displayed as a drop-down list with only 3 locales. This makes the management of translations quite cumbersome. As explained [here](https://github.com/decidim/decidim/pull/6462), the dropdown should be shown when there are more than 4 locales.

**To Reproduce**
1. Log in as admin in meta.decidim.org
2. Enter any process
4. See dropdown

**Expected behavior**
That locales are displayed as tabs. 

**Screenshots**
Current behavior
![](https://i.imgur.com/5FFBWQ4.png)

Expected behavior
![](https://i.imgur.com/m5KTDtv.png)

**Extra data (please complete the following information):**
 - Device: Desktop
 - Device OS: Ubuntu 22.04
 - Browser: Chrome
 - Decidim Version: 0.27
 - Decidim installation: Metadecidim

**Additional context**
I couldn't reproduce it in either Nightly or Try, so I guess it's a Metadecidim bug.

**Comment by ahukkanen** [comment]
This was actually already fixed at decidim/decidim#9902 but it wasn't correctly labelled which is why I think we missed it for the 0.27.1 release.

I have created the backports for this at decidim/decidim#10087.

**Comment by ahukkanen** [comment]
This is fixed by the 0.27.2 release which has been just deployed to Metadecidim.

I will close this issue as fixed.

Fixed by #116.
