### ISSUE TITLE
Enable external users to be organization admin

### ISSUE THREAD

**Issue by ZephOne** [decidim/metadecidim#115]
Hi,
currently if an external user (via omniauth-cas) is invited to be an admin of an organization, this does not work.
User can't do any action without having to change its password.

If the user change its password which should not be done, the has not become admin.

**Comment by ahukkanen** [comment]
I believe this is a problem that concerns all Decidim instances, not only Metadecidim.

I have therefore elevated this issue to the core repository as decidim/decidim#10398.

**Comment by alecslupu** [comment]
@ZephOne A simple workaround, is to add to your decidim initializer:
  
```
  config.admin_password_strong = false
```

**Comment by ZephOne** [comment]
@alecslupu it's even more than a workaround for me, it seems to be the solution.
