### ISSUE TITLE
Feature Request - Voting by shares

### ISSUE THREAD

**Issue by develop-Greenant** [decidim/metadecidim#118]
We are interesting in using Decidim for managing an Owners Corporation website.

The main limitation we have found is that we need to have voting by shares.

For example, some owners who will be voting have only 1 share, while others have 10 shares.  Therefore, we would like the ability to apply a weight to the voting, so that an owner with 10 shares has this reflected in their vote.

Would it be possible to add such a feature, in which a user profile also records their share so that it is applied in votes?

**Comment by alecslupu** [comment]
Hello!

Decidim does not offer this kind of functionality. Since this is not a feature requested by many people, you could develop this as a stand alone plugin. 

You could use : https://meta.decidim.org/processes/roadmap to properly submit a feature request.

**Comment by alecslupu** [comment]
I am closing the ticket, since the question has been replied. Please open a proposal in metadecidim otherwise.
