### ISSUE TITLE
Home page crash on install

### ISSUE THREAD

**Issue by mattstone** [decidim/metadecidim#37]
Hello,

I've just installed decidim from Gem and it crashed when I tried to load the home page.

An easy fix 0 

line 53 in lib/decidim/engine_router.rb should be

 method_name.to_s.match(/_(url|path)$/)

![screen shot 2019-02-14 at 11 36 34 am](https://user-images.githubusercontent.com/20787/52754541-fbb47200-304e-11e9-8d1a-9c239ccaf4fe.png)

**Comment by oriolgual** [comment]
Which Ruby version are you using? `match?` is a valid method for a String in Ruby 2.6

**Comment by mattstone** [comment]
ah - thanks for that. Was using ruby 2.3.1 - using 2.6.1 has sorted the issue for me.
