### ISSUE TITLE
Crash in Proposals

### ISSUE THREAD

**Issue by mattstone** [decidim/metadecidim#39]
Hello,

I'm trying to create a proposal.

This is the user view.  When I click on the "Your submission must be greater than 15 characters"

![Screen Shot 2019-03-11 at 10 14 05 am](https://user-images.githubusercontent.com/20787/54093006-e41aa000-43e6-11e9-8070-b3c51a72d45a.png)

I get this crash - note: the proposal does not have any participatory_text's

![Screen Shot 2019-03-11 at 10 15 10 am](https://user-images.githubusercontent.com/20787/54093022-10362100-43e7-11e9-9bd5-e1264745d521.png)

**Comment by oriolgual** [comment]
@mattstone could you please report this to https://meta.decidim.org/processes/bug-report ? We're trying to dog-food Decidim and use it as our bugtracker.
