### ISSUE TITLE
Crash on a debates page

### ISSUE THREAD

**Issue by deivid-rodriguez** [decidim/metadecidim#7]
https://meta.decidim.barcelona/processes/welcome/f/169/?locale=es

![crash](https://user-images.githubusercontent.com/2887858/34062706-d9ab7766-e1cc-11e7-8554-5a24365f7528.png)

**Comment by ahukkanen** [comment]
I believe this issue no longer concerns MetaDecidim.

The current URL for the linked component with the language selection is this one:
https://meta.decidim.org/processes/Decidim4Dummies/f/169/?locale=es

And this seems to work fine.

Therefore, closing this issue.
