### ISSUE TITLE
Decidim How To: Add a new Language

### ISSUE THREAD

**Issue by MohammedSalahadin** [decidim/metadecidim#81]
Need a step by step guide on how to add a new language to decidim application.
I already have crowdin Account but I don't know how to use it.

**Comment by shirgoldbird** [comment]
@MohammedSalahadin have you read https://docs.decidim.org/en/develop/managing_translations_i18n/#_adding_a_new_language? If you want a new language added to Crowdin, the first thing you need to do is open a new issue in the main Decidim repo to get the language added. (Here's [an example](https://github.com/decidim/decidim/issues/6640).)
