### ISSUE TITLE
Button for accepting/rejecting a proposal is missing in meta.decidim

### ISSUE THREAD

**Issue by Alicia-Mullor** [decidim/metadecidim#9]
As an admim, I cannot accept/reject a proposal in meta.decidim.barcelona because the button is missing.

**Comment by josanFFiG** [comment]
Reply bottom is gone.
![captura de 2017-12-18 12-16-45](https://user-images.githubusercontent.com/27766903/34104198-cc0eaf54-e3ef-11e7-8797-68c73570d411.png)

**Comment by josepjaume** [comment]
Bug hunted here: https://github.com/decidim/metadecidim/issues/9
